### ISSUE TITLE
docs for fuzzing + auth scan

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/docs#27]

**Comment by ccosta-pd** [comment]
@tarunKoyalwar  I think we can just create a new auth scan page and add the fuzzing content to the existing content here https://docs.projectdiscovery.io/templates/protocols/http/fuzzing-overview

Let me know if I can help, I'm happy to migrate content directly from the blog if you can point me at where that content should go!

**Comment by tarunKoyalwar** [comment]
yes, that's what i was thinking, fuzzing can furthur be split into more sub-pages since we have more 2-3x more fuzzing content compared to existing fuzzing documentation, initial draft would give us a rough idea and we can restructure later as we see fit
