### ISSUE TITLE
X-Team-id header parameter is not documented

### ISSUE THREAD

**Issue by vthiery** [projectdiscovery/docs#69]
The `X-Team-id` header must be passed to actually hit the resources in a team workspace.
The current openapi spec does not document this header.

**Comment by ehsandeep** [comment]
@vthiery thanks! docs are now [updated](https://docs.projectdiscovery.io/api-reference/introduction) to reflect this optional header input.

![image](https://github.com/user-attachments/assets/8f0c989a-944a-4a3b-860a-9cbdd19080c0)
